chore: fix: default set container conflict
Some events can't be mixed with 'container=new'.

This fixes integration tests failures like:

--- FAIL: Test_EventFilters/trace_only_events_from_new_containers