libbpfgo: bump to commit 5e89006 to include fixes
libbpfgo recently added 2 needed fixes:

commit 5e89006 ("libbpfgo: use perf_buffer__new new API and fix style")
and commit 5d2336e ("kprobe: remove legacy kprobes and unneeded
includes").

Together they fix a panic happening in main branch:

    $ sudo ./dist/tracee-ebpf
    TIME             UID    COMM             PID     TID...
    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x2 addr=...

whenever libbpf executes perf_buffer__new() using the old, and
deprecated, prototype. This change makes sure that libbpfgo will always
call perf_buffer__new() using the new prototype.

Fix: #1383