chore: static checker fixes
Fix the following static checker errors:

  pkg/bufferdecoder/decoder_test.go:53:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:74:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:95:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:116:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:136:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:157:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:178:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:198:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:219:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:240:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:261:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:282:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:334:2: should merge variable declaration with assignment on next line (S1021)
  pkg/bufferdecoder/decoder_test.go:447:6: func generateContextBytes is unused (U1000)
  pkg/bufferdecoder/eventsreader.go:159:32: should use make([]uint64, 0) instead (S1019)
  pkg/ebpf/events_derived.go:179:63: should use make([]bufferdecoder.HookedSyscallData, 0) instead (S1019)
  pkg/ebpf/events_processor.go:236:5: the surrounding loop is unconditionally terminated (SA4004)
  pkg/ebpf/initialization/kconfig.go:34:12: unnecessary assignment to the blank identifier (S1005)
  pkg/ebpf/initialization/kconfig.go:39:12: unnecessary assignment to the blank identifier (S1005)
  pkg/ebpf/tracee.go:1271:12: error strings should not end with punctuation or newlines (ST1005)
  pkg/ebpf/tracee.go:1281:70: file mode '444' evaluates to 0674; did you mean '0444'? (SA9002)
  pkg/ebpf/user_mode_events_test.go:9:6: func getProcNamespaces is unused (U1000)
  pkg/ebpf/write_capture.go:15:3: const S_IFMT is unused (U1000)
  pkg/events/sorting/cpu_queue.go:39:6: this value of err is never used (SA4006)
  pkg/events/sorting/cpu_queue.go:39:12: Errorf is a pure function but its return value is ignored (SA4017)
  pkg/events/sorting/pool.go:32:6: should omit comparison to bool constant, can be simplified to node.isAllocated (S1002)
  pkg/events/sorting/sorting.go:245:4: should omit comparison to bool constant, can be simplified to cq.IsUpdated (S1002)
  pkg/events/sorting/sorting_test.go:28:2: redundant return statement (S1023)
  signatures/golang/examples/example.go:14:6: type counter is unused (U1000)
  signatures/golang/examples/example.go:21:21: func (*counter).Init is unused (U1000)
  signatures/golang/examples/example.go:28:21: func (*counter).GetMetadata is unused (U1000)
  signatures/golang/examples/example.go:36:21: func (*counter).GetSelectedEvents is unused (U1000)
  signatures/golang/examples/example.go:44:21: func (*counter).OnEvent is unused (U1000)
  signatures/golang/examples/example.go:70:21: func (*counter).OnSignal is unused (U1000)